CREATE TABLE MEDICO(
CLAVE INTEGER NOT NULL,
NOMBRE VARCHAR(24) NOT NULL,
APPATERNO VARCHAR(24) NOT NULL,
APMATERNO VARCHAR(24) NOT NULL,
ESPECIALIDAD VARCHAR(24) NOT NULL,
CONSTRAINT CLAVE_CTE_PK PRIMARY KEY (CLAVE)
);

CREATE TABLE ENFERMERA(
CLAVE INTEGER NOT NULL,
NOMBRE VARCHAR(24) NOT NULL,
APPATERNO VARCHAR(24) NOT NULL,
APMATERNO VARCHAR(24) NOT NULL,
TURNO VARCHAR(24) NOT NULL,
CONSTRAINT CLAVE_CTE_PK PRIMARY KEY (CLAVE)
);

CREATE TABLE PACIENTE(
CLAVE INTEGER NOT NULL,
NOMBRE VARCHAR(24) NOT NULL,
APPATERNO VARCHAR(24) NOT NULL,
APMATERNO VARCHAR(24) NOT NULL,
ENFERMEDAD VARCHAR(24) NOT NULL,
MEDICAMENTO VARCHAR(24) NOT NULL,
CONSTRAINT CLAVE_CTE_PK PRIMARY KEY (CLAVE)
);

CREATE TABLE ENFERMEDAD(
CLAVE INTEGER NOT NULL,
DESCRIPCION VARCHAR(24) NOT NULL,
CONSTRAINT CLAVE_CTE_PK PRIMARY KEY (CLAVE)
);

CREATE TABLE MEDICAMENTO(
CLAVE INTEGER NOT NULL,
NOMBRE VARCHAR(24) NOT NULL,
CONSTRAINT CLAVE_CTE_PK PRIMARY KEY (CLAVE)
);

CREATE TABLE ASIGNACIONMEDICO(
CLAVEASIG INTEGER NOT NULL,
NOMBREM VARCHAR(24) NOT NULL,
CLAVEM INTEGER NOT NULL,
NOMBREP VARCHAR(24) NOT NULL,
CLAVEP INTEGER(24) NOT NULL,
CONSTRAINT CLAVE_ASIG PRIMARY KEY (CLAVEASIG)
);

CREATE TABLE ASIGNACIONENFERMERA(
CLAVEASIG INTEGER NOT NULL,
NOMBREE VARCHAR(24) NOT NULL,
CLAVEE INTEGER NOT NULL,
NOMBREP VARCHAR(24) NOT NULL,
CLAVEP INTEGER(24) NOT NULL,
CONSTRAINT CLAVE_ASIG PRIMARY KEY (CLAVEASIG)
);